/* The lifted showcase engines (Thulaib's ChatGPT master, restored 7 Oct 2026): scoped reveals, the films loop,
   the photography wall, the laptop scroller and the posts ring. Each one returns quietly when its section is absent. */
(function(){var r=document.querySelectorAll('.cx [data-reveal],.cx .about-showpiece-head,.cx .video-reference-top,.cx .post-ribbon-head,.cx .website-gallery-head');function show(){r.forEach(function(e){if(e.getBoundingClientRect().top<innerHeight-40)e.classList.add('in')})}addEventListener('scroll',show,{passive:true});show();setTimeout(show,400);})();
(function(){var windowEl=document.getElementById('video-loop-window');var strip=document.getElementById('video-loop-strip');if(!windowEl||!strip)return;var previous=document.getElementById('video-loop-prev');var next=document.getElementById('video-loop-next');var toggle=document.getElementById('video-loop-toggle');var reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;var originals=Array.from(strip.children);var paused=reduced;var visible=true;var touching=false;var last=0;var position=0;if(!reduced){originals.forEach(function(card){var clone=card.cloneNode(true);clone.setAttribute('aria-hidden','true');strip.appendChild(clone)})}function cycleWidth(){return strip.scrollWidth/2}function normalise(){var cycle=cycleWidth();if(!cycle)return;while(position>=cycle)position-=cycle;while(position<0)position+=cycle;windowEl.scrollLeft=position}function frame(time){if(last&&visible&&!paused&&!touching){position+=(time-last)*.03;normalise()}last=time;requestAnimationFrame(frame)}function move(direction){paused=true;position=windowEl.scrollLeft;setToggle();windowEl.scrollBy({left:direction*Math.min(windowEl.clientWidth*.62,340),behavior:reduced?'auto':'smooth'})}function setToggle(){toggle.textContent=paused?'▶':'❚❚';toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'Play video reel':'Pause video reel')}function togglePlayback(){paused=!paused;position=windowEl.scrollLeft;setToggle()}previous.addEventListener('click',function(){move(-1)});next.addEventListener('click',function(){move(1)});toggle.addEventListener('click',togglePlayback);windowEl.addEventListener('keydown',function(event){if(event.key==='ArrowLeft'){event.preventDefault();move(-1)}if(event.key==='ArrowRight'){event.preventDefault();move(1)}if(event.key===' '){event.preventDefault();togglePlayback()}});windowEl.addEventListener('pointerdown',function(){touching=true;position=windowEl.scrollLeft;windowEl.classList.add('dragging')});function release(){touching=false;position=windowEl.scrollLeft;windowEl.classList.remove('dragging');normalise()}windowEl.addEventListener('pointerup',release);windowEl.addEventListener('pointercancel',release);if('IntersectionObserver' in window){var observer=new IntersectionObserver(function(entries){visible=entries[0].isIntersecting},{threshold:.08});observer.observe(windowEl)}setToggle();requestAnimationFrame(frame)})();
(function(){'use strict';var photo=document.getElementById('photo-scroll-container'),plane=document.getElementById('photo-plane');if(!photo||!plane)return;var cols=Array.from(photo.querySelectorAll('.scroll-photo-col'));var rm=matchMedia('(prefers-reduced-motion:reduce)').matches||document.documentElement.classList.contains('cap');var target=0,cur=0,running=false;function clamp(v){return Math.min(Math.max(v,0),1)}function mix(a,b,p){return a+(b-a)*p}function setTarget(){if(rm||innerWidth<780){target=1;return}var r=photo.getBoundingClientRect();target=clamp(-r.top/Math.max(r.height-innerHeight,1))}function render(p){if(innerWidth<780||rm){plane.style.transform='';cols.forEach(function(c){c.style.transform=''});return}var rp=clamp(p/.5),sp=clamp((p-.5)/.4),cp=clamp((p-.5)/.5);plane.style.transform='rotateX('+mix(75,0,rp)+'deg) scale('+mix(1.2,1,sp)+')';var s=[-10,15,-10],e=[2,5,2];cols.forEach(function(c,i){c.style.transform='translateY('+mix(s[i]||0,e[i]||0,cp)+'%)'})}function draw(){running=false;cur+=(target-cur)*(rm?1:.085);if(Math.abs(target-cur)<.0005)cur=target;render(cur);if(Math.abs(target-cur)>.0005)start()}function start(){if(running)return;running=true;requestAnimationFrame(draw)}function update(){setTarget();start()}addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update()})();
(function(){'use strict';var portfolio=document.getElementById('portfolio-intro'),title=document.getElementById('portfolio-title'),device=document.getElementById('portfolio-device');if(!portfolio||!title||!device)return;var rm=matchMedia('(prefers-reduced-motion:reduce)').matches||document.documentElement.classList.contains('cap');var target=0,cur=0,running=false;function clamp(v){return Math.min(Math.max(v,0),1)}function mix(a,b,p){return a+(b-a)*p}function setTarget(){var r=portfolio.getBoundingClientRect();target=rm?1:clamp((innerHeight-r.top)/(innerHeight+r.height))}function render(p){if(rm){device.style.transform='';title.style.transform='';return}var s0=innerWidth<=768?.7:1.05,s1=innerWidth<=768?.9:1;device.style.transform='rotateX('+mix(20,0,p)+'deg) scale('+mix(s0,s1,p)+')';title.style.transform='translateY('+mix(0,-100,p)+'px)'}function draw(){running=false;cur+=(target-cur)*(rm?1:.085);if(Math.abs(target-cur)<.0005)cur=target;render(cur);if(Math.abs(target-cur)>.0005)start()}function start(){if(running)return;running=true;requestAnimationFrame(draw)}function update(){setTarget();start()}addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update()})();
(function(){
'use strict';
var orbit=document.getElementById('post-orbit');
var shell=document.getElementById('post-orbit-shell');
var previous=document.getElementById('post-orbit-prev');
var next=document.getElementById('post-orbit-next');
var pause=document.getElementById('post-orbit-pause');
if(!orbit||!shell||!previous||!next||!pause)return;
var reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
var angle=0;
var paused=reduced;
var dragging=false;
var startX=0;
var startAngle=0;
var last=performance.now();
var resumeAt=0;
function paint(){orbit.style.setProperty('--post-orbit-angle',angle+'deg')}
function setPause(value){paused=value;pause.setAttribute('aria-pressed',String(value));pause.textContent=value?'Resume motion':'Pause motion'}
function step(direction){angle+=direction*45;resumeAt=performance.now()+2600;paint()}
function animate(now){var delta=Math.min(now-last,34);last=now;if(!paused&&!dragging&&now>resumeAt)angle+=delta*.007;paint();requestAnimationFrame(animate)}
previous.addEventListener('click',function(){step(-1)});
next.addEventListener('click',function(){step(1)});
pause.addEventListener('click',function(){setPause(!paused)});
/* a press only becomes a drag once the finger moves; a tap stays a tap on the card (7 Oct 2026: the capture on press swallowed every tap) */
var pending=false,justDragged=false;shell.addEventListener('pointerdown',function(event){if(event.pointerType==='mouse'&&event.button!==0)return;pending=true;startX=event.clientX;startAngle=angle});
shell.addEventListener('pointermove',function(event){if(pending&&!dragging&&Math.abs(event.clientX-startX)>6){dragging=true;shell.classList.add('is-dragging');try{shell.setPointerCapture(event.pointerId)}catch(e){}}if(!dragging)return;angle=startAngle+(event.clientX-startX)*.24;paint()});
shell.addEventListener('click',function(event){if(justDragged){event.preventDefault();event.stopPropagation();justDragged=false}},true);
function release(event){pending=false;if(!dragging)return;dragging=false;justDragged=true;setTimeout(function(){justDragged=false},400);resumeAt=performance.now()+2200;shell.classList.remove('is-dragging');if(shell.hasPointerCapture(event.pointerId))shell.releasePointerCapture(event.pointerId)}
shell.addEventListener('pointerup',release);
shell.addEventListener('pointercancel',release);
if(reduced){pause.disabled=true;pause.textContent='Motion reduced';pause.setAttribute('aria-pressed','true');paint()}else requestAnimationFrame(animate);
})();
